import type { GetStaticProps, InferGetStaticPropsType, NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import Image from "next/image";
import { Payment } from "../lib/payments";
import { User } from "../lib/users";
import { getRandomPayment } from "../payments";
import styles from "../styles/Home.module.css";

const fetcher = (...args: unknown[]) => {
  // @ts-ignore
  return fetch(...args).then((res) => res.json());
};

export const getStaticProps: GetStaticProps<{
  users: User[];
  payment: Payment[];
}> = async () => {
  const users: { data: User[] } = await fetcher("http://localhost:8080/users");
  const randomPayment = await getRandomPayment();
  return {
    props: {
      users: users.data,
      payment: [...(randomPayment ?? [])],
    },
  };
};

const DynamicPayments = dynamic(
  async () => {
    const mod = await import("../ui/loading-payments");

    return mod.PaymentsUI;
  },
  {
    loading: () => <p>Loading...</p>,
  }
);

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = (
  props
) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Circle Takehome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <DynamicPayments users={props.users} payment={[]} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
